name: Run changelog script

on:
  push:
    branches:
      - main
  schedule:
    # Runs every day at 10:00 AM CET (Central European Time)
    - cron: '0 9 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run changelog script
        env:
          TOKEN_GITHUB_API: ${{ secrets.TOKEN_GITHUB_API }}
          TOKEN_AIRTABLE: ${{ secrets.TOKEN_AIRTABLE }}
        run: python changelog.py