# .github/workflows/qualify.yml
name: Qualify raw items

on:
  schedule:
    # ── run at 05:00 UTC from last Sunday of March → last Sunday of Oct
    - cron:  '0 5 * * *'
    # ── run at 06:00 UTC for the rest of the year (CET / winter time)
    - cron:  '0 6 * * *'
  workflow_dispatch:      # manual trigger button in the Actions UI

jobs:
  qualify:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: INFO
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      TOKEN_GITHUB_API: ${{ secrets.TOKEN_GITHUB_API }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run qualifier batch
        run: |
          python -m qualifiers.run_all