# .github/workflows/qualify.yml
name: Qualify raw items

on:
    # run every day at 6am CET (Central European Time)
    schedule:
      - cron: '0 6 * * *'
    # also run on every push to main so you spot errors quickly
    push:
      branches: [main]

jobs:
  qualify:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: INFO
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      TOKEN_GITHUB_API: ${{ secrets.TOKEN_GITHUB_API }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run qualifier batch
        run: |
          python -m qualifiers.run_all